# @package stimulus

kind: natural_image
stimulus_size: 2.0
baseline_rate: 0.0
resolution: 128
luminance: 1.0
contrast: 1.0
temporal_frequency: 0.0
visual_gain: 400.0
n_theta: 8

gabor:
  sigma: 0.085
  gamma: 1.0
  spatial_frequency: 14.137166941154069
  phase: 0.0
