# @package model

layers:
  periodic: true
  l4:
    n_side: 40
    region_size: 2.0
    z_pos: 0.0
    all_tuned: true
  l23:
    n_side: null
    region_size: 2.0
    z_pos: 0.1
    inhibitory_fraction: null
    random_inhibitory: false

connectivity:
  p_ee: 0.12
  j: 3.0
  g: 5.5
  equalize_indegree: true
  scales:
    ee: 1.0
    ei: 1.08
    ex: 1.0
    ie: 1.0
    ii: 1.0
    ix: 1.0
  kernel:
    sigma_narrow: 0.075
    sigma_broad: 0.225
    kappa: 0.45

trained_network_path: null
